### PR TITLE
Added Radial Layout Algorithm for Rose Trees

### PR DESCRIPTION
**Pull request by prash471**

### CODE REVIEW

**Comment by byorgey** [comment]
Hi @prash471, thanks!  This is looking nice.  Can you fix the warnings that are causing the Travis build to fail? (The other problem you were seeing with the Travis build has now been fixed.)

**Comment by prash471** [comment]
Hello @byorgey, I have removed all the warnings. You can merge it now. Sorry for being late.

**Comment by byorgey** [comment]
@prash471, thanks for the great addition!  Sorry it took me so long to get around to merging it.

**Comment by prash471** [comment]
@byorgey Thank you sir, working on some more diagrams problems.

**Pull request merged**
