### PR TITLE
Update for GHC-7.10

### PR DESCRIPTION
**Pull request by bergey**
This builds locally against the just-rebased
https://github.com/diagrams/diagrams-lib/pull/239

It's a squashed version of the `travis` branch of this repo, without the
changes to diagrams-travis needed for travis to build it.

### CODE REVIEW

**Comment by byorgey** [comment]
I just restarted the Travis build to see if it builds cleanly now.  ...Actually, I just realized it won't, because the other day I pushed a commit adding the diagrams-solve dependency, I didn't realize it was in this PR.

**Comment by bergey** [comment]
Yes, sorry - I slipped in some "make it build" changes unrelated to 7.10.  Do you want a rebased PR so it will merge cleanly?

**Comment by byorgey** [comment]
Why don't you just go ahead and merge it manually (which is the same work you'd have to do to rebase it).  It looks good to me.

**Comment by byorgey** [comment]
Actually, I take it back --- the travis build failed because of something about a redundant import of `Control.Lens`, not because of merge conflicts.  Do you know what that's about?

**Comment by bergey** [comment]
Exporting `Control.Lens` from `Diagrams.Prelude` broke everything downstream.

**Comment by byorgey** [comment]
Ah, of course.  No worries, we can fix that separately.

**Pull request merged**
