### PR TITLE
Tree.hs: hide Empty from Diagrams.Prelude

### LINKED ISSUE #56: Namespace conflict in Diagrams.TwoD.Layout.Tree
D:\diagrams-contrib\src\Diagrams\TwoD\Layout\Tree.hs: line 187, column 18:
      Ambiguous occurrence `Empty'
        It could refer to either `Diagrams.TwoD.Layout.Tree.Empty',
                                 defined at src\Diagrams\TwoD\Layout\Tree.hs:182:16
                              or `Diagrams.Prelude.Empty',
                                 imported from `Diagrams.Prelude' at src\Diagrams\TwoD\Layout\Tree.hs:163:1-33
                                 (and originally defined in `Control.Lens.Empty')
    D:\diagrams-contrib\src\Diagrams\TwoD\Layout\Tree.hs: line 187, column 24:
      Ambiguous occurrence `Empty'
        It could refer to either `Diagrams.TwoD.Layout.Tree.Empty',
                                 defined at src\Diagrams\TwoD\Layout\Tree.hs:182:16
                              or `Diagrams.Prelude.Empty',
                                 imported from `Diagrams.Prelude' at src\Diagrams\TwoD\Layout\Tree.hs:163:1-33
                                 (and originally defined in `Control.Lens.Empty')

`Empty` is both defined locally (for the `BTree` type) and imported from `lens` via `Diagrams.Prelude`. This breaks compilation for me, both from Hackage (1.3.0.6) and GitHub (1.3.1).

### PR DESCRIPTION
**Pull request by tejon**
Fixes #56.

### CODE REVIEW

**Comment by byorgey** [comment]
This is the simplest fix, but anyone using `Diagrams.TwoD.Layout.Tree` and importing `Diagrams.Prelude` will still run into the same issue. Another alternative would be to hide `Empty` from the lens import so it is not re-exported from `Diagrams.Prelude`.  We do this for some other things from `lens`, see https://github.com/diagrams/diagrams-lib/blob/master/src/Diagrams/Prelude.hs#L81.  Anyone have any

**Comment by tejon** [comment]
I went with this fix because it can't break existing code. Agreed that the other option is superior in general, but it warrants a bump to 1.4 on the wild chance that someone is actually using that Prelude export. Not something I was comfortable tossing into a cold-call pull request. :)

**Comment by tejon** [comment]
Just to be comprehensive about it: the third option is to rename the local one e.g. `BTEmpty`. That breaks code too, but does have the end result of no toys taken away.

**Comment by cchalmers** [comment]
I vote we rename it to `BEmpty`, I can see the `Empty` pattern in lens being useful.  We could also add an `AsEmpty` instance so if they enable `PatternSynonyms` they can still use `Empty` for the empty tree.

**Comment by byorgey** [comment]
Hmm, the third option sounds the best, but that also technically requires a major version bump. =(  I propose we just merge this as-is, to get a buildable version out quickly, and then implement the third option to be released at some point in the future when we put out diagrams 1.4.

**Comment by cchalmers** [comment]
Sounds good to me.

**Comment by byorgey** [comment]
Released as `diagrams-contrib-1.3.0.7`.

**Pull request merged**
